In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

1

In [6]:
matriz[0,1]

2

In [7]:
arr[0:3]

array([1, 2, 3])

In [8]:
arr[-1]

9

In [9]:
arr[-3:]

array([7, 8, 9])

In [10]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])