In [2]:
import numpy as np

In [7]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
piece_arr = arr[0:6]

In [10]:
piece_arr[:] = 0
piece_arr

array([0, 0, 0, 0, 0, 0])

In [11]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
# """copy() nos permite copiar un array de NumPy en otra variable de tal forma que 
# al modificar el nuevo array los cambios no se vean reflejados en array original.""""
arr_copy = arr.copy()
arr_copy[:] = 10
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [13]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])