In [1]:
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.linspace(0, 10 , 10)    # (no. inicio, no. final, no. datos que quiero en el array)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand()

0.30249255675463693

In [9]:
np.random.rand(4)    # genera un array de una dimension

array([0.8675309 , 0.1816843 , 0.11558706, 0.9491666 ])

In [10]:
np.random.rand(3, 3)

array([[0.23114667, 0.05863608, 0.42212814],
       [0.40864548, 0.16399048, 0.97452327],
       [0.19736501, 0.56290339, 0.29597644]])

In [15]:
np.random.randint(1, 15)

3

In [14]:
np.random.randint(1, 100, (4, 4))

array([[54, 17, 92, 21],
       [81, 25, 49, 44],
       [54, 33, 27,  2],
       [12, 41, 42, 14]])