In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim     # nos muestra el numero de dimensiones

42


0

In [3]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [7]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


3

## Agregar o eliminar dimensiones

In [8]:
vector = np.array([1, 2, 3], ndmin=10)    #no. de dimensiones = 10
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [9]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)    #axis = 0 expande una dimension a nivel de filas
print(expand)
expand.ndim

[[1 2 3]]


2

In [10]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)    # para controlar las dimensiones
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
