In [2]:
import numpy as np

### Con python

In [4]:
# con python
lista = [1, 2]
lista

[1, 2]

In [5]:
lista * 2

[1, 2, 1, 2]

### Con numpy

In [7]:
# con numpy
arr = np.arange(0, 10)
arr2 = arr.copy()

### Operaciones

In [8]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
1 / (arr + 1)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [10]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
matriz = arr.reshape(2, 5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
matriz2 = matriz.copy()
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [14]:
matriz2.T   # transpuesta de matriz

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
np.matmul(matriz, matriz2.T)   # producto punto

array([[ 30,  80],
       [ 80, 255]])

In [16]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])