In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)

In [4]:
matriz = arr.reshape(2, 5)
print(matriz)

[[15 10 17 10 13]
 [ 4 18 16  1 10]]


In [5]:
print(arr)
print("-------------------")
print(arr.max())

[15 10 17 10 13  4 18 16  1 10]
-------------------
18


In [6]:
print(matriz.max())

18


In [7]:
# maximos por fila en la matriz
print(matriz.max(1))
#maximos por columna en la misma matriz 
print(matriz.max(0))

[17 18]
[15 18 17 10 13]


In [8]:
print(arr.argmax())   #muestra el indice mas pequeño(por si se repite) del valor más grande del array

6


In [9]:
print(matriz.argmax(1))
print(matriz.argmax(0))

[2 1]
[0 1 0 0 0]


In [10]:
print(arr.min())
print("-----------------")
print(matriz.min(0))
print("-----------------")
print(matriz.min(1))

1
-----------------
[ 4 10 16  1 10]
-----------------
[10  1]


In [11]:
print(arr.argmin())
print("-----------------")
print(matriz.argmin(0))
print("-----------------")
print(matriz.argmin(1))

8
-----------------
[1 0 1 1 1]
-----------------
[1 3]


In [12]:
print(arr.ptp())   # pic to pic, del valor mas pequeño del array al mas grande cuanta diferencia hay
print("-----------------")
print(matriz.ptp(0))     #column
print("-----------------")
print(matriz.ptp(1))    #row

17
-----------------
[11  8  1  9  3]
-----------------
[ 7 17]


In [13]:
print(np.percentile(arr, 0))   # el valor mas pequeño del arrary
print(np.percentile(arr, 50))    # el valor en medio del array
# como no hay mitad exacta, el resultado es resultado de operar 13 y 4, los dos de en medio del array
print(np.percentile(arr, 100))    # el valor mas alto del array

1.0
11.5
18.0


In [17]:
arr.sort()   # ordena del menor al mayor
arr

array([ 1,  4, 10, 10, 10, 13, 15, 16, 17, 18])

In [20]:
np.median(arr)    # similar a percentil 50

11.5

In [21]:
np.median(matriz, 0)    # mediana

array([ 7. ,  9.5, 13. , 13.5, 14. ])

In [22]:
np.median(matriz, 1)

array([10., 16.])

In [23]:
np.std(arr)    # desviacion standar

5.295280917949491

In [24]:
np.var(arr)    # varianza, np.std(arr)**2

28.04

In [25]:
np.mean(arr)    # media o promedio, también funciona con matrices

11.4

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])     # como no es de las mismas dimensiones que a

In [27]:
b = np.expand_dims(b, axis = 0)    # expande una dimension
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
b.T    # transpuesta de la matriz b

array([[5],
       [6]])

In [30]:
np.concatenate((a, b.T), axis = 1)    # tambien pudimos usar reshape

array([[1, 2, 5],
       [3, 4, 6]])