In [1]:
import numpy as np

In [18]:
arr = np.random.randint(1, 10, (3, 2))

In [19]:
arr.shape     #me indica cuantas filas y columnas tengo

(3, 2)

In [20]:
arr.reshape(1, 6)    #cambia la forma establecida de un array
#np.reshape(arr, (1, 6))    #el ultimo digito es 0 al no. elementos

array([[1, 5, 1, 3, 7, 7]])

In [21]:
arr.reshape(2, 3)

array([[1, 5, 1],
       [3, 7, 7]])

In [23]:
np.reshape(arr, (2, 3), 'C')

array([[1, 5, 1],
       [3, 7, 7]])

In [24]:
np.reshape(arr, (2, 3), 'F')

array([[1, 7, 3],
       [1, 5, 7]])